name: Sahil Shekhawat
description: My programming adventures
meta_description: "Sahil Shekhawat's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://sahilshekhawat.me'
google_analytics: 'UA-62563604-1'

# Details for the RSS feed generator
url:            'http://sahilshekhawat.github.io'
author:         'Sahil Shekhawat'
